/*
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
 four million, find the sum of the even-valued terms.
*/
const LIMIT: i32 = 4_000_000;

pub fn solve() {
    let mut result: i32 = 0;
    let mut a: i32 = 1;
    let mut b: i32 = 2;

    while a <= LIMIT {
        if is_even(a) {
            result += a;
        }
        let a_new = b;
        let b_new = a + b;
        a = a_new;
        b = b_new;
    }
    println!("The sum of all even fibonacci numbers below {} is {}", LIMIT, result)
}

fn is_even(n: i32) -> bool {
    n % 2 == 0
}
